package br.ufpi.easii.iscool.enuns;

public enum NivelDeFormacao {
	GRADUADO_COMPLETO, GRADUADO_INCOMPLETO, DOUTORADO_COMPLETO, DOUTORADO_INCOMPLETO, MESTRADO_COMPLETO, MESTRADO_INCOMPLETO, 
	ESPECIALIZADO_COMPLETO, ESPECIALIZADO_INCOMPLETO
}
